### ISSUE TITLE
how to switch from PS C:\Users\______  to  PS D: inseng\dvpl_converter.exe, also what does inseng mean in english?

### ISSUE THREAD

**Issue by sameguy-from-wotb** [Tankerch/DVPL_Converter#3]

**Comment by AAAOldSix666** [comment]
Input the  command  _D:_  first and then input  _D: \inseng\dvpl_converter.exe_

_inseng_ maybe no meaning in English~

**Comment by Tankerch** [comment]
"iseng" is indonesian for "random", just my folder for all of my random projects
