### ISSUE TITLE
not being able to open DVPL tool

### ISSUE THREAD

**Issue by BlueARL44** [Tankerch/DVPL_Converter#5]
![Screenshot (119)](https://github.com/Tankerch/dvpl_converter/assets/166122235/6df39967-6c2a-4453-a2fc-0408cbc01091)
![Screenshot (120)](https://github.com/Tankerch/dvpl_converter/assets/166122235/0097f135-9595-417a-a3bb-b61062b28efa)
I have a hard time figuring out how to launch or execute the tool...I have read the "read me" but I am still at a loss. the CMD/Terminal thing I don't seem to grasp the working of it.

**Comment by AAAOldSix666** [comment]
First ,open cmd.exe and then input   _cd path/to/the/dvplconverter_  (For example ,if this tool in directory  C:/Users/aaa/bbbb/ you need to input _cd  C:/Users/aaa/bbbb/_).Second,input the name of this tool and press _Enter_  .Third,choose **encrypt** or **decrypt** by button ↑ or ↓ on the keyboard ,and then continuing by tips(Attention: the .dvpl file you want to convert or the file you want to convert to the .dvpl file and this tool must in the same directory!)

**Comment by BlueARL44** [comment]
![Screenshot (121)](https://github.com/Tankerch/dvpl_converter/assets/166122235/28b16545-0d5f-4812-b3c6-120dfc3cd807)
![Screenshot (122)](https://github.com/Tankerch/dvpl_converter/assets/166122235/801e2a6c-9bc1-4910-9b83-86df98afc25c) Okay it opens now...but it says failed to access it? even though its already within the same folder...?
